"""Add is_available field to Movie model

Revision ID: b0dd30c7e7a9
Revises: c0bb005751bc
Create Date: 2026-06-05 10:43:36.503620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dd30c7e7a9'
down_revision: Union[str, Sequence[str], None] = 'c0bb005751bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'movies',
        sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'is_available')
    # ### end Alembic commands ###
