"""create_orders_models_v2

Revision ID: c0bb005751bc
Revises: 8741b24de6ed
Create Date: 2026-06-03 15:07:21.039080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0bb005751bc'
down_revision: Union[str, Sequence[str], None] = '8741b24de6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE orderstatusenum AS ENUM ('PENDING', 'PAID', 'CANCELED')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE orders ALTER COLUMN status TYPE orderstatusenum "
        "USING status::text::orderstatusenum"
    )
    op.execute("DROP TYPE statusenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("CREATE TYPE statusenum AS ENUM ('PENDING', 'PAID', 'CANCELED')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE orders ALTER COLUMN status TYPE statusenum "
        "USING status::text::statusenum"
    )
    # ### end Alembic commands ###
    op.execute("DROP TYPE orderstatusenum")
