"""Add payment_intent_id field to Payment model

Revision ID: dae9217f6efd
Revises: cc2273dd83f8
Create Date: 2026-06-08 14:43:28.581460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae9217f6efd'
down_revision: Union[str, Sequence[str], None] = 'cc2273dd83f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_intent_id')
    # ### end Alembic commands ###
